ipni/indexstar

.github/workflows/ecr-publisher.yml
On merge to `main` and publication of a release publish container images
to a ECR repository dedicated to hosting indexstar images.
The repository is set up and configured as part of storetheindex
infrastructure.
=> Publish container images to ECR

find.go, server.go
Handle `GET /cid/{cid}` and `POST /multihash` the other two flavours of
storehtinedex find APIs.
=> Handle other find endpoints and do not serve root URL

server.go
Do not include `/` suffix in reframe handler URI otherwise requests
from the client will not match.
=> Fix incorrect `reframe` handler URI

go.mod, reframe.go
If the configured backend URL ended with `/` the previous join resulted
in invalid reframe URL. This meant that all reframe queries would have
returned empty result.
Go `1.19` adds utilities for safely joining elements to the path URL.
Since indexstar does not need Go `1.18` support, upgrade the module and
take advantage of the new utility to construct the correct path for
remote reframe endpoints.
=> Fix a bug in `reframe` path concatenation

go.mod, go.sum
Upgrade to latest to avoid potential client side issues when decoding
multiple provider info from find providers response via refame. Note
that this doesn't impact us right now since every indexer always returns
a single response. But proactively upgrade to avoid future issues should
they return multiple results.
=> Upgrade to the latest delegated routing

providers.go
storetheindex never returns 404 on GET to `/providers` even when there
are no providers. Instead, it returns an empty JSON list. Do the same
in indexstar.
Note that this was never happening anyway due to the condition that
was never true; the `resp` was being checked for nil instead of len
zero.
=> Combined providers should never return 404

config.go, reframe.go, reframe_translator.go, server.go
Add the ability to configure dialer timeout and keep-alive duration for reframe, reframe translator and the http server.
=> Make HTTP Dialer settings configurable

find.go, reframe_translator.go, server.go
* Use same find-scatter method for reframe translator
* use request context in scatter-gather rather than context.background (may help some timeout errors)
=> update reframe translator to use find codepath

find.go, reframe.go, scatter_gather.go, scatter_gather_test.go
* make sure all channels are drained in cases where context is canceled.
* simplify the interface to scatter/gather - timing is on contexts, rather than on gather stopping returning.
=> Simplify scatter/gather

reframe_translator.go
When translating reframe requests include providers that support more than one transport which includes bitswap instead of expecting exactly one transport that is bitswap.
Relates to:
* https://github.com/filecoin-project/storetheindex/issues/977
=> Include Bitswap providers that support more than one transport

providers.go
Check the number of returned success results from backend before marshalling response to `GET /provider/<pid>`.
Fixes: #40
=> Do not return 200 on unknown providers

delegated_translator.go, server.go
The HTTP delegated routing uses `GET /routing/v1/providers/{CID}` to lookup CIDs. Translate the CID lookup URI. For the translation introduced in #45 to work correctly, the URI needs to be changed to `/cid/{CID}`.
Since delegated translator instantiates its own mux, on server handler mapping the URI prefix needs to be stripped.
=> Fix CID lookup in delegated routing URI translation

delegated_translator.go, metrics/server.go
Count the number of calls made to the HTTP delegated routing tagged by method.
Explicitly return `501 Not Implemented` on `PUT` to `/routing/v1/providers`. This is to identify that putting provider records is not currently implemented by `cid.contact`.
Relates to:
- https://github.com/ipfs/specs/pull/337#discussion_r1047399812
Fixes #54
=> Count HTTP delegated routing calls by method and return 501 on `PUT`

delegated_translator.go, find.go, providers.go, server.go
Only accept and forward expected HTTP methods in order to reduce exposure surface of internal services.
=> Tighten up checks for HTTP method before handling

find.go, server.go
* Proxy metadata requests that are used for double hashed lookups
* The data is scattered across the same list of backends as is used for finds
* Returns the first found metadata instead of gathering across all responses
Fixes https://github.com/ipni/indexstar/issues/60
=> Start proxying metadata requests

find.go, find_ndjson.go, header.go
Check the `Accept` request header and if it explicitly states support for ndjson media type, then respond with streaming provider results.
Check uniqueness of results with first-found strategy, where a result that has already been sent back will not be included again. The check for uniqueness is done by hashing the provider ID and context ID of a record using IEEE crc32.
Fixes #65
=> Implement support for `ndjson` streaming response on IPNI find APIs

find_ndjson.go, header.go, header_test.go
Fix a bug where values should be split by delimiter before using the mime parser.
Fix a bug where ndjhson channel does not get closed and leaves requests hanging when processing has finished.
=> Fix Accept header check bug

config.go, find_ndjson.go
Separate the config for max wait when handing streaming requests with a default of 20 seconds.
Increase the default client timeout to 30 seconds, because that is the maximum the client will wait regardless of context timeout. Therefore, lower value will render result max wait time useless.
=> Separate max wait config for streaming response

config.go, config_test.go, find.go
Handle `OPTIONS` requests as dictated by IPNI spec, and include cascade labels when configured.
Fixes #72
=> Handle `OPTIONS` requests according to IPNI spec

find.go, find_ndjson.go
Adjust logged parameters to avoid base64 encoding of the response body on unsuccessful response code.
=> Refine logging for better human readability

find.go, find_ndjson.go
Some incoming requests seem to be missing `Accept` header, and are rejected as bad request by `caskadht` but not storetheindex.
To avoid all of this, when finding providers in non-streaming path, set `Accept` header explicitly to JSON, because what we return to the client in this case will be JSON.
=> Set `Accept` header on find

find.go, providers.go
Do not attempt to decode providers response unless the status is OK.
Set `Accept` header explicitly wherever the response from backends is parsed as JSON.
Fix logging of endpoint to host only to reduce noise in logs.
=> Only parse providers response on OK response

find.go, find_ndjson.go, go.mod, main.go, server.go
DHT lookups take longer to complete in comparison with IPNI search. This is why streaming response was introduced such that results are returned as soon as they are found instead of having to wait for all results before returning any.
Internally, indexstar uses a circuit breaker mechanism that would exclude slow backends from the search space. The max wait for non-streaming requests is set to 5 seconds. When a client uses non-streaming `Accept` header with DHT lookup cascade enabled, there is a high chance that the response would take longer than the internal timeout of 5 seconds, which results in the DHT cascade endpoints to eventually be excluded from the search space.
To avoid this, the changes here introduce an option to always translate non-streaming requests to streaming ndjson, and …
=> Implement non-streaming translation to reduce 404s on dht cascading

backend.go, config.go, find.go, find_ndjson.go, main.go, providers.go, reframe.go, reframe_translate_test.go, scatter_gather.go, scatter_gather_test.go, server.go
Refactor backend instantiation such that circuit breaker backends are individually configurable. Reflect changes across the repo.
Add the ability to check if a backend matches a request before attempting to call it. This avoids response slow-down caused by slow backends early in the chain
Introduce a separate configuration to mark cascade lookup backends with explicit matcher in order to avoid routing all requests to them.
Relates to:
- https://github.com/ipni/indexstar/issues/86
=> Make backend CB individually configurable and separate cascade

find_ndjson.go
Wrong counter for graphsync was being incremented.
=> Fix bug in metrics related to response transport measure

find.go, metrics/server.go, server.go
Add tag foundCaskade and foundRegular into FindLatency metric that aims to help to understand what backends contributed to the output
=> Add a metric to track backend type

.gitignore, find.go
Handle batch find, that uses a POST request, the same whether or not --translateNonStreaming is specified.
Fixes #94
=> Allow batch find when --translateNonStreaming

find.go, find_ndjson.go, scatter_gather.go
Timeouts is a part of normal flow especially for caskade backends and hence shouldn't be logged as warnings or errors.
=> Lower the log level for context timeouts

delegated_translator.go, find.go, find_ndjson.go, providers.go, reframe_translate_test.go, reframe_translator.go, server.go
Add special backend types for handling providers and double hashed requests. We need to start having specialisation as the number of different backends grows and scatter gather across everything becomes inefficient.
Fixes https://github.com/ipni/storetheindex/issues/1913
=> Add providers and dh backends

index.html, main.go, server.go
Instead if recursively routing `/` to the first configured backed explicitly render the iframe.
This reduces fragility of the way landing page is rendered by making it
independent of backend servers
=> Route web UI iframe via indexstar server

find_ndjson.go
It seems that extended providers add metadata to the same context ID. When checking for duplicate results include metadata so that results with extra metadata are not excluded.
=> Include metadata when checking for result uniqueness

config.go, config_test.go, find.go
Now that reframe is no longer supported, remove all config related to it.
=> Remove redundant reframe configuration

main.go, server.go
`indexstar` now embeds the cid.contact landing page. As a result there is no need to reverse proxy the root to a backend nor fallback mechanism for it.
=> Remove fallback and base routing

go.mod, go.sum, providers.go, server.go
Periodically gets provider information from all sources to provide. Provides a unified view of all provider information, with high-performance concurrent reads.
=> Use go-libipni pcache package to retrieve and cache provider info

delegated_translator.go, find.go
Always use nil client request body when GET requests have no body.
=> Fix panic resulting from empty byte reader

.github/workflows/ecr-publisher.yml, delegated_translator.go, find.go, find_ndjson.go, providers.go, server.go, version.json
The delegated find path in `delegated_translator.go` was being was being formed incorrectly, and did not remove the "providers/" part of the path.
The fix was to change this:
```go
uri := r.URL.JoinPath("../cid", cidUrlParam)
```
to this:
```go
uri := r.URL.JoinPath("../../cid", cidUrlParam)
```
=> Fix delegated find path

delegated_translator.go
The /routing/v1/providers/ endpoint now reports unknown schema as "peer", and omits the Protocol.
Testing was manual testing using example in issue.
Fixes #147
=> Use "peer" schema for unknown providers at /routing/v1/providers

delegated_translator.go
Makes the `/routing/v1/providers` endpoint comply with the Peer Schema: https://specs.ipfs.tech/routing/http-routing-v1/#peer-schema
I changed all the current providers since they're all technically peers. Also note that I changed the protocol string to an array since we now send all protocols for the same peer in the same record. The metadata is implemented per protocol, hence a custom `MarshalJSON`.
=> fix: convert to peer schema with multiple protocols

version.json
Bump version file in prep for release.
=> Tag `v0.1.8` release

find.go
Allows hex formatted multihashes to be used with the `/multihash/` and `/encrypted/multihash/` endpoints.
See also:
- https://github.com/ipni/specs/pull/31
- https://github.com/ipni/go-libipni/pull/209
=> Find can handle hex formatted multihashes

delegated_translator.go, find_ndjson.go, server.go
Can maybe simplify code a bit as the delegated routing endpoint won't work with the encrypted results, so some of the complexity built for that isn't needed in this path.
Could add complexity to block on the `doFindStreaming` until the first result so that it can properly return a 404 in cases where there are are no results.
=> Add ndjson semantics to delegated routing endpoint
