ipni/indexstar

providers.go, reframe.go, server.go
increase reframe client config
=> add providers indexstar support

providers.go
Fix a bug where no providers were being returned due to a negative check
in combine logic.
Reuse existing struct type to decode response from storetheindex.
=> Fix a bug in combining providers and reuse existing model

reframe.go
Reduce the reframe client timeout to 5 seconds to make upstream timeout
less likely. 5 seconds aslo seems like a big enough value for
connections to local indexer instances.
When collecting reframe responses, do not wait for any results when the
context is done already. In this case there is no point collecting any
further results.
=> Reduce reframe timeout and do not wait for results when context is done

server.go
=> add health handler

config.go, config_test.go, find.go, go.mod, go.sum, reframe.go, server.go
Set up configuration via environment variables with existing values as default if unset.
=> Add the ability to configure indexstar from environment variables

go.mod, go.sum, reframe.go, reframe_translator.go
Upgrade to the latest delegated routing dependency.
=> Upgrade delegated routing dependency

reframe_translator.go
=> dedup returned peer ids for reframe

config.go, find.go, go.mod, go.sum, reframe_translate_test.go, scatter_gather.go, server.go
=> Add circuit breakers for servers contacted by find

config.go, go.mod, go.sum, main.go, server.go
fix #35 
note: once we're happy with the update logic, we'll need to use the same configmap deploy setup as in storetheindex for getting servers into a config file that can be updated by k8s
=> reload backend servers from file

delegated_translator.go, find.go, metrics/server.go, reframe_translator.go
* Record method (get vs post) on latency metric as intended
* Add metric for amount of requests split by {http, reframe, delegated} handler
=> Improve indexstar metrics

delegated_translator.go
`PUT` requests are sent to the root of `/routing/v1/providers`. This won't match the pattern of current `find` handler function. Separate the handler and explicitly return `501`.
Relates to: #54
=> Fix response to `PUT` at root of `/routing/v1/providers`

find.go
Fix a bug where no encrypted results are returned if there are no unencrypted results.
Simplify `doFind` by returning a nil slice instead of an empty one which
is the same in net functionality.
Fixes #61
=> Fix encrypted result check bug

find_ndjson.go
Handle streaming of results gathered from ndjson using a bespoke channel since the implementation of scatter gather is not tuned for gathering channel of channels.
=> Fix streaming of results in ndjson scatter gather

find.go, find_ndjson.go
Circuit breaker is opened on error. Fix a bug where bad request (400) would have also returned an error which would result in circuit opening due to bad request.
The fix only returns error on 500 and higher status codes.
=> Do not return error on `4xx` to avoid circuit opening

version.json
Tag a release as it has been a while.
=> Bump version for release

find.go, find_ndjson.go
Wrap remaining errors that should be marked as success by the circuit breaker.
=> Wrap re-triable errors with Mark As Success for circuit breaker

find.go, find_ndjson.go, reframe.go, scatter_gather.go
On `Done`, the circuit breaker library checks the `ctx` error separately from the error that is passed in along with the context. Separately, it is also configured to not fail on context cancelled.
On scatter gather, a new context with cancel is created with some max wait time and then passed to the function to perform the action. The fix here passes the same context as the one passed to do the action to the circuit breaker `Done` function so that the config for context cancellation is respected.
The changes here also improve context handling in scatter gather such that as soon as the processing is finished the context is cancelled, and all channels are closed up properly without the need for draining when context is done.
=> Fix a bug where wrong context is passed to circuit breaker

find.go
Fix bug that caused underreporting of `foundRegular` and `foundCaskade` flags when results get found in one backend only.
=> Update found metrics reporting

delegated_translator.go
Records returned from IPNI via Delegated Routing don't have ContextID in them. Becuase of that, some records that are valid from the IPNI point of view might look like duplicates from the Delegated Routing point of view. To make the Delegated Routing output nicer, deduplicate identical records.
Fixes https://github.com/ipni/storetheindex/issues/1760
=> Deduplicate Delegated Routing outputs

main.go
=> Add CLI args for new backends

version.json
All latest changes have been working on dev for a while, so time to bump version.
=> Create new release version
